package cmd

const webUIHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>npc web UI</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
<style>
:root{--npc-accent:#2f80ed;--npc-cyan:#27c5d8;--npc-soft:#eef6ff;--npc-dark:#111827}
body{font-size:15px}.content-wrapper{background:#f4f7fb}.dark-mode .content-wrapper{background:#101418}
.brand-icon{height:38px;width:38px;border-radius:10px;display:grid;place-items:center;font-weight:800}
.polish-gradient{background:linear-gradient(135deg,var(--npc-accent),var(--npc-cyan));color:#fff}
.card,.small-box{border-radius:.75rem}.card{box-shadow:0 14px 40px rgba(15,23,42,.08);border:0}
.dark-mode .card,.dark-mode .small-box{box-shadow:0 16px 42px rgba(0,0,0,.32)}
.hero{border-radius:1rem;padding:1.35rem 1.5rem;margin-bottom:1rem;color:#fff;background:linear-gradient(135deg,#0f4c81,#00a6a6)}
.hero h1{font-size:1.55rem;margin:0 0 .35rem}.hero p{max-width:860px;margin:0;opacity:.92}
.section-title{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:.4rem 0 .8rem}
.section-title h2{font-size:1.05rem;margin:0;font-weight:700}.section-title p{margin:0;color:#6c757d}
.form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}
.control-card{background:#f8fafc;border:1px solid #e3e8ef;border-radius:.75rem;padding:1rem;height:100%}
.dark-mode .control-card{background:#17202a;border-color:#2b3947}
.help-panel{border-left:4px solid var(--npc-accent);background:var(--npc-soft);border-radius:.55rem;padding:.85rem 1rem;color:#263238}
.dark-mode .help-panel{background:#132338;color:#dce8f7}.help-panel h4{font-size:.95rem;margin:0 0 .35rem;font-weight:700}
.muted-help{font-size:.86rem;color:#6c757d;margin:.3rem 0 0}.dark-mode .muted-help{color:#aeb7c2}
.check-row{display:flex;flex-wrap:wrap;gap:.55rem 1rem;margin:.75rem 0}
.check-row label{font-weight:500;margin:0}.table td,.table th{vertical-align:middle;white-space:nowrap}.table-wrap{overflow-x:auto}
.path{max-width:300px;overflow:hidden;text-overflow:ellipsis}.table-actions{display:flex;gap:.35rem;flex-wrap:wrap}.mini-form{display:inline}
.step-badge{display:inline-grid;place-items:center;width:1.65rem;height:1.65rem;border-radius:50%;background:var(--npc-accent);color:#fff;font-weight:700;margin-right:.45rem}
.profile-pills{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.75rem}.profile-pill{border:1px solid #dce4ee;border-radius:.7rem;padding:.75rem;background:#fff}
.dark-mode .profile-pill{background:#141c24;border-color:#2b3947}.profile-pill strong{display:block}.profile-pill span{font-size:.83rem;color:#6c757d}.dark-mode .profile-pill span{color:#aeb7c2}
.nav-tabs .nav-link{border-top-left-radius:.65rem;border-top-right-radius:.65rem}.main-footer{font-size:.875rem}
</style>
</head>
<body class="hold-transition sidebar-mini layout-fixed dark-mode">
<div class="wrapper">
<nav class="main-header navbar navbar-expand navbar-dark">
<ul class="navbar-nav"><li class="nav-item"><a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a></li><li class="nav-item d-none d-sm-inline-block"><span class="nav-link">Reverse proxy control plane</span></li></ul>
<ul class="navbar-nav ml-auto"><li class="nav-item"><button id="themeToggle" class="btn btn-sm btn-outline-info"><i class="fas fa-adjust"></i> Theme</button></li></ul>
</nav>
<aside class="main-sidebar sidebar-dark-primary elevation-4">
<a href="/" class="brand-link"><span class="brand-icon polish-gradient brand-image elevation-2">npc</span><span class="brand-text font-weight-light">Proxy Configurator</span></a>
<div class="sidebar"><nav class="mt-3"><ul class="nav nav-pills nav-sidebar flex-column"><li class="nav-item"><a class="nav-link active" href="/"><i class="nav-icon fas fa-columns"></i><p>Overview</p></a></li><li class="nav-item"><a class="nav-link" href="#workflows"><i class="nav-icon fas fa-magic"></i><p>Workflows</p></a></li><li class="nav-item"><a class="nav-link" href="#certificates"><i class="nav-icon fas fa-certificate"></i><p>Certificates</p></a></li><li class="nav-item"><a class="nav-link" href="/api/sites"><i class="nav-icon fas fa-code"></i><p>Sites API</p></a></li><li class="nav-item"><a class="nav-link" href="/api/status"><i class="nav-icon fas fa-heartbeat"></i><p>Status API</p></a></li></ul></nav></div>
</aside>
<div class="content-wrapper">
<section class="content-header"><div class="container-fluid">
<div class="hero"><div class="d-flex justify-content-between align-items-start flex-wrap"><div><h1>Nginx Proxy Dashboard</h1><p>Create, edit, secure, and import reverse proxies without writing Nginx by hand. Risky operations still require confirmation and run through npc safety checks.</p></div><span class="badge badge-light mt-2">npc {{.Version}}</span></div></div>
</div></section>
<section class="content"><div class="container-fluid">
<div class="row">
<div class="col-lg-3 col-6"><div class="small-box polish-gradient"><div class="inner"><h3>{{index .Status "active_sites"}}</h3><p>Active sites</p></div><div class="icon"><i class="fas fa-toggle-on"></i></div></div></div>
<div class="col-lg-3 col-6"><div class="small-box bg-secondary"><div class="inner"><h3>{{index .Status "disabled_sites"}}</h3><p>Disabled sites</p></div><div class="icon"><i class="fas fa-toggle-off"></i></div></div></div>
<div class="col-lg-3 col-6"><div class="small-box bg-success"><div class="inner"><h3>{{index .Status "nginx_active"}}</h3><p>Nginx active</p></div><div class="icon"><i class="fas fa-heart"></i></div></div></div>
<div class="col-lg-3 col-6"><div class="small-box bg-info"><div class="inner"><h3>{{index .Status "matched_sites"}}</h3><p>Total managed</p></div><div class="icon"><i class="fas fa-layer-group"></i></div></div></div>
</div>
{{if .Notice}}<div class="alert alert-{{.Notice.Kind}}"><strong>{{.Notice.Title}}</strong><br>{{.Notice.Message}}</div>{{end}}
<div class="row" id="workflows">
<div class="col-lg-8"><div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-plus-circle mr-2"></i>Create a reverse proxy</h3></div><div class="card-body">
<form method="post" action="/actions"><input type="hidden" name="action" value="create">
<div class="section-title"><h2><span class="step-badge">1</span>Route traffic to a backend</h2><p>Required</p></div>
<div class="form-grid"><div class="form-group"><label>Public hostname</label><input name="hostname" class="form-control" placeholder="app.example.com" required><p class="muted-help">The domain users open in their browser.</p></div><div class="form-group"><label>Backend host</label><input name="backend_host" class="form-control" value="127.0.0.1" required><p class="muted-help">IP, DNS name, localhost, or reachable container name.</p></div><div class="form-group"><label>Backend port</label><input name="backend_port" type="number" min="1" max="65535" class="form-control" value="3000" required><p class="muted-help">The port your app listens on.</p></div><div class="form-group"><label>Backend scheme</label><select name="backend_scheme" class="form-control"><option>http</option><option>https</option></select><p class="muted-help">Use https only when the backend itself serves TLS.</p></div></div>
<div class="section-title mt-3"><h2><span class="step-badge">2</span>Choose behavior</h2><p>Safe defaults</p></div>
<div class="form-grid"><div class="form-group"><label>Profile</label><select name="profile" class="form-control profile-select"><option>generic</option><option>websocket</option><option>upload</option><option>streaming</option><option>docker</option><option>security-basic</option></select><p class="muted-help">Profiles set normal Nginx timeouts, buffering, and defaults.</p></div><div class="form-group"><label>Body size</label><input name="client_max_body_size" class="form-control" value="100M"><p class="muted-help">Maximum upload/request body accepted by Nginx.</p></div></div>
<div class="help-panel profile-help"><h4>Generic profile</h4><p class="mb-0">Good for normal web apps. Uses conservative timeouts and keeps proxy buffering enabled.</p></div>
<div class="check-row"><label><input type="checkbox" name="websocket"> WebSocket headers</label><label><input type="checkbox" name="access_log" checked> Access log</label><label><input type="checkbox" name="error_log" checked> Error log</label><label><input type="checkbox" name="force"> Replace existing managed site</label></div>
<div class="section-title mt-3"><h2><span class="step-badge">3</span>HTTPS options</h2><p>Optional</p></div>
<div class="check-row"><label><input type="checkbox" name="ssl"> Enable SSL</label><label><input type="checkbox" name="acme"> Issue with acme.sh</label><label><input type="checkbox" name="redirect_https" checked> Redirect HTTP to HTTPS</label><label><input type="checkbox" name="http2" checked> HTTP/2</label></div>
<div class="form-grid"><div class="form-group"><label>Existing fullchain path</label><input name="cert_path" class="form-control" placeholder="/etc/ssl/app/fullchain.pem"></div><div class="form-group"><label>Existing key path</label><input name="key_path" class="form-control" placeholder="/etc/ssl/app/privkey.pem"></div><div class="form-group"><label>ACME method</label><select name="acme_method" class="form-control"><option value="http">HTTP-01</option><option value="dns">DNS-01</option><option value="standalone">Standalone</option></select></div><div class="form-group"><label>DNS provider</label><input name="dns_provider" class="form-control" placeholder="cloudflare"><p class="muted-help">Used for DNS-01 when provider secrets exist.</p></div></div>
<label class="mt-2"><input type="checkbox" name="confirm" value="yes" required> I reviewed the route, profile, and HTTPS settings</label><br><button class="btn btn-info mt-2"><i class="fas fa-save mr-1"></i>Create site</button></form>
</div></div></div>
<div class="col-lg-4">
<div class="card card-outline card-info"><div class="card-header"><h3 class="card-title"><i class="fas fa-compass mr-2"></i>Profile guide</h3></div><div class="card-body"><div class="profile-pills"><div class="profile-pill"><strong>generic</strong><span>Normal dashboards and web apps.</span></div><div class="profile-pill"><strong>websocket</strong><span>Realtime apps that keep browser connections open.</span></div><div class="profile-pill"><strong>upload</strong><span>Large forms, imports, and file uploads.</span></div><div class="profile-pill"><strong>streaming</strong><span>SSE, long polling, media, or slow streamed responses.</span></div><div class="profile-pill"><strong>docker</strong><span>Local container backends reached from the host.</span></div><div class="profile-pill"><strong>security-basic</strong><span>Internal tools needing stricter headers and auth-ready defaults.</span></div></div></div></div>
<div class="card card-outline card-info"><div class="card-header"><h3 class="card-title"><i class="fas fa-file-import mr-2"></i>Import existing configs</h3></div><div class="card-body"><p class="text-muted">Adopt manually created or third-party Nginx configs from sites-available. Import reads existing certificate paths and backend settings before npc writes metadata.</p><form method="post" action="/actions"><input type="hidden" name="action" value="import"><div class="form-group"><label>Config path, optional</label><input name="path" class="form-control" placeholder="/etc/nginx/sites-available/app.conf"><p class="muted-help">Leave empty to scan all configs.</p></div><label><input type="checkbox" name="force"> Refresh existing metadata</label><br><label><input type="checkbox" name="confirm" value="yes" required> Import configs</label><br><button class="btn btn-outline-info mt-2">Import</button></form></div></div>
</div></div>
<div class="row"><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-edit mr-2"></i>Edit site</h3></div><div class="card-body"><form id="editForm" method="post" action="/actions"><input type="hidden" name="action" value="edit"><div class="form-grid"><div class="form-group"><label>Site</label><select name="hostname" class="form-control site-picker">{{range .Sites}}<option data-host="{{.BackendHost}}" data-port="{{.BackendPort}}" data-scheme="{{.BackendScheme}}" data-profile="{{.Profile}}" data-body="{{.ClientMaxBodySize}}" data-websocket="{{.WebSocket}}" data-redirect="{{.RedirectHTTPS}}" data-http2="{{.HTTP2}}" data-cert="{{.CertificatePath}}" data-key="{{.CertificateKeyPath}}" data-acme="{{.ACME}}" data-method="{{.ACMEMethod}}" data-provider="{{.DNSProvider}}">{{.Hostname}}</option>{{end}}</select><p class="muted-help">Selecting a site fills the known values below.</p></div><div class="form-group"><label>Backend host</label><input name="backend_host" class="form-control"></div><div class="form-group"><label>Backend port</label><input name="backend_port" type="number" min="1" max="65535" class="form-control"></div><div class="form-group"><label>Backend scheme</label><select name="backend_scheme" class="form-control"><option>http</option><option>https</option></select></div><div class="form-group"><label>Profile</label><select name="profile" class="form-control profile-select"><option>generic</option><option>websocket</option><option>upload</option><option>streaming</option><option>docker</option><option>security-basic</option><option>imported</option></select></div><div class="form-group"><label>Body size</label><input name="client_max_body_size" class="form-control"></div></div><div class="help-panel profile-help"><h4>Profile details</h4><p class="mb-0">Select a profile to see what it changes.</p></div><div class="check-row"><label><input type="checkbox" name="websocket"> WebSocket headers</label><label><input type="checkbox" name="redirect_https"> HTTPS redirect</label><label><input type="checkbox" name="http2"> HTTP/2</label><label><input type="checkbox" name="no_reload"> Skip reload</label></div><label class="mt-2"><input type="checkbox" name="confirm" value="yes" required> Apply edit</label><br><button class="btn btn-info mt-2">Save changes</button></form></div></div></div>
<div class="col-lg-6" id="certificates"><div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-certificate mr-2"></i>Certificates</h3></div><div class="card-body"><div class="help-panel mb-3"><h4>How to choose</h4><p class="mb-0"><strong>HTTP-01</strong> is easiest when the domain already points to this server and ports 80/443 are reachable. <strong>DNS-01</strong> is better for Cloudflare, private origins, wildcard certificates, or locked-down firewalls. Existing certificates only attach paths that already work on disk.</p></div>
<ul class="nav nav-tabs" role="tablist"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#issueCert">Issue ACME</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#setCert">Attach existing</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#deleteCert">Remove</a></li></ul>
<div class="tab-content pt-3"><div class="tab-pane active" id="issueCert"><form method="post" action="/actions"><input type="hidden" name="action" value="cert-issue"><div class="form-grid"><div class="form-group"><label>Site</label><select name="hostname" class="form-control site-picker">{{range .Sites}}<option data-method="{{.ACMEMethod}}" data-provider="{{.DNSProvider}}" data-redirect="{{.RedirectHTTPS}}" data-http2="{{.HTTP2}}">{{.Hostname}}</option>{{end}}</select></div><div class="form-group"><label>Validation method</label><select name="method" class="form-control"><option value="http">HTTP-01</option><option value="dns">DNS-01</option></select><p class="muted-help">DNS-01 uses provider APIs; HTTP-01 uses a temporary Nginx challenge route.</p></div><div class="form-group"><label>DNS provider</label><input name="dns_provider" class="form-control" placeholder="cloudflare"><p class="muted-help">For Cloudflare, configure provider secrets once and npc reuses them.</p></div><div class="form-group"><label>Email, optional</label><input name="email" class="form-control"><p class="muted-help">Let's Encrypt is the default CA.</p></div></div><input type="hidden" name="acme_ca" value="letsencrypt"><div class="check-row"><label><input type="checkbox" name="redirect_https" checked> Redirect HTTP to HTTPS</label><label><input type="checkbox" name="http2" checked> HTTP/2</label><label><input type="checkbox" name="no_reload"> Skip reload</label></div><label><input type="checkbox" name="confirm" value="yes" required> Issue and install this certificate</label><br><button class="btn btn-success mt-2">Issue certificate</button></form></div>
<div class="tab-pane" id="setCert"><form id="certSetForm" method="post" action="/actions"><input type="hidden" name="action" value="cert-set"><div class="form-grid"><div class="form-group"><label>Site</label><select name="hostname" class="form-control site-picker">{{range .Sites}}<option data-cert="{{.CertificatePath}}" data-key="{{.CertificateKeyPath}}" data-acme="{{.ACME}}" data-method="{{.ACMEMethod}}" data-provider="{{.DNSProvider}}" data-redirect="{{.RedirectHTTPS}}" data-http2="{{.HTTP2}}">{{.Hostname}}</option>{{end}}</select></div><div class="form-group"><label>Fullchain path</label><input name="cert_path" class="form-control" required><p class="muted-help">Usually fullchain.pem or fullchain.cer.</p></div><div class="form-group"><label>Private key path</label><input name="key_path" class="form-control" required><p class="muted-help">Must be readable by Nginx and kept private.</p></div><div class="form-group"><label>DNS provider</label><input name="dns_provider" class="form-control"></div></div><div class="check-row"><label><input type="checkbox" name="manual" checked> Manual certificate</label><label><input type="checkbox" name="acme"> acme.sh managed</label><label><input type="checkbox" name="redirect_https" checked> HTTPS redirect</label><label><input type="checkbox" name="http2" checked> HTTP/2</label></div><label><input type="checkbox" name="confirm" value="yes" required> Update certificate metadata and Nginx config</label><br><button class="btn btn-info mt-2">Set certificate</button></form></div>
<div class="tab-pane" id="deleteCert"><form method="post" action="/actions"><input type="hidden" name="action" value="cert-delete"><div class="form-group"><label>Site</label><select name="hostname" class="form-control">{{range .Sites}}<option>{{.Hostname}}</option>{{end}}</select></div><div class="help-panel mb-2"><h4>Destructive options</h4><p class="mb-0">Removing metadata switches the site back to HTTP-only. Deleting files also removes certificate material from disk.</p></div><div class="check-row"><label><input type="checkbox" name="keep_acme"> Keep acme.sh registration</label><label><input type="checkbox" name="remove_files"> Delete cert files</label><label><input type="checkbox" name="no_reload"> Skip reload</label></div><label><input type="checkbox" name="confirm" value="yes" required> Remove certificate from site</label><br><button class="btn btn-danger mt-2">Delete certificate</button></form></div></div></div></div></div></div>
<div class="row"><div class="col-12"><div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-globe mr-2"></i>Managed sites</h3></div><div class="card-body p-0 table-wrap"><table class="table table-hover table-striped mb-0"><thead><tr><th>Hostname</th><th>State</th><th>SSL</th><th>Backend</th><th>Profile</th><th>Group</th><th>Tags</th><th>Actions</th><th>Config</th></tr></thead><tbody>
{{range .Sites}}<tr><td><strong>{{.Hostname}}</strong></td><td><span class="badge badge-{{if eq .State "on"}}success{{else}}secondary{{end}}">{{.State}}</span></td><td><span class="badge badge-{{if eq .SSL "yes"}}success{{else}}warning{{end}}">{{.SSL}}</span></td><td><code>{{.Backend}}</code></td><td>{{.Profile}}</td><td>{{.Group}}</td><td>{{.Tags}}</td><td><div class="table-actions"><form class="mini-form" method="post" action="/actions"><input type="hidden" name="action" value="enable"><input type="hidden" name="hostname" value="{{.Hostname}}"><input type="hidden" name="confirm" value="yes"><button class="btn btn-xs btn-success">Enable</button></form><form class="mini-form" method="post" action="/actions"><input type="hidden" name="action" value="disable"><input type="hidden" name="hostname" value="{{.Hostname}}"><input type="hidden" name="confirm" value="yes"><button class="btn btn-xs btn-secondary">Disable</button></form><form class="mini-form" method="post" action="/actions"><input type="hidden" name="action" value="delete"><input type="hidden" name="hostname" value="{{.Hostname}}"><input type="hidden" name="remove_metadata" value="on"><input type="hidden" name="confirm" value="yes"><button class="btn btn-xs btn-danger" onclick="return confirm('Delete {{.Hostname}} metadata?')">Delete</button></form></div></td><td class="path" title="{{.Config}}">{{.Config}}</td></tr>{{else}}<tr><td colspan="9" class="text-muted">No npc-managed sites found.</td></tr>{{end}}
</tbody></table></div></div></div></div>
<div class="row"><div class="col-12"><div class="card"><div class="card-header"><h3 class="card-title"><i class="fas fa-info-circle mr-2"></i>Runtime</h3></div><div class="card-body"><dl class="row mb-0"><dt class="col-md-2">Config</dt><dd class="col-md-10 text-truncate">{{index .Status "config_file"}}</dd><dt class="col-md-2">Sites available</dt><dd class="col-md-10 text-truncate">{{index .Status "sites_available"}}</dd><dt class="col-md-2">Nginx version</dt><dd class="col-md-10 text-truncate">{{index .Status "nginx_version"}}</dd></dl></div></div></div></div>
</div></section></div>
<footer class="main-footer"><strong>npc web UI</strong><span class="float-right d-none d-sm-inline">Task-based AdminLTE interface with dark mode.</span></footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
<script>
const themeKey='npc-webui-theme';
const saved=localStorage.getItem(themeKey);
if(saved==='light'){document.body.classList.remove('dark-mode')}
document.getElementById('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark-mode');localStorage.setItem(themeKey,document.body.classList.contains('dark-mode')?'dark':'light')});
const profileCopy={
 generic:['Generic profile','Best for normal web apps, dashboards, and admin tools. It uses 60 second read timeouts, keeps buffering on, and starts with a 100M body limit.'],
 websocket:['WebSocket profile','For realtime apps. It keeps connections open longer and disables buffering so live updates are not delayed.'],
 upload:['Upload profile','For file uploads, imports, and slow clients. It raises the body limit and uses longer timeouts so uploads are less likely to be interrupted.'],
 streaming:['Streaming profile','For SSE, long polling, media, and responses that arrive gradually. It disables buffering and keeps reads open much longer than generic.'],
 docker:['Docker profile','For local container backends. It keeps the standard proxy behavior but makes container-host routing the expected workflow.'],
 'security-basic':['Security-basic profile','For private tools that need stricter defaults. Combine it with Basic Auth, allowlists, and security headers where appropriate.'],
 imported:['Imported profile','Used when npc adopted an existing config and should preserve behavior until you deliberately choose another preset.']
};
function checked(form,name,value){const el=form.querySelector('[name="'+name+'"]'); if(el) el.checked=value==='true'}
function setProfileHelp(form){
 const select=form.querySelector('.profile-select'); const box=form.querySelector('.profile-help'); if(!select||!box) return;
 const copy=profileCopy[select.value]||profileCopy.generic; box.innerHTML='<h4>'+copy[0]+'</h4><p class="mb-0">'+copy[1]+'</p>';
}
function fillForm(form){
 const select=form.querySelector('.site-picker'); if(!select) {setProfileHelp(form); return}
 const o=select.options[select.selectedIndex]; if(!o) return;
 const set=(name,value)=>{const el=form.querySelector('[name="'+name+'"]'); if(el && value!==undefined) el.value=value};
 set('backend_host',o.dataset.host); set('backend_port',o.dataset.port); set('backend_scheme',o.dataset.scheme);
 set('profile',o.dataset.profile); set('client_max_body_size',o.dataset.body); set('method',o.dataset.method);
 set('cert_path',o.dataset.cert); set('key_path',o.dataset.key); set('dns_provider',o.dataset.provider);
 checked(form,'websocket',o.dataset.websocket); checked(form,'redirect_https',o.dataset.redirect); checked(form,'http2',o.dataset.http2); checked(form,'acme',o.dataset.acme);
 setProfileHelp(form);
}
document.querySelectorAll('form').forEach(form=>{fillForm(form); const site=form.querySelector('.site-picker'); if(site) site.addEventListener('change',()=>fillForm(form)); const profile=form.querySelector('.profile-select'); if(profile) profile.addEventListener('change',()=>setProfileHelp(form));});
</script>
</body>
</html>`
